# GitHub Actions Environment Variables
# This file documents all required secrets and variables for GitHub Actions

# Required Secrets (set in GitHub repository settings)
secrets:
  # Bot Configuration
  BOT_TOKEN: "Your Telegram bot token"
  ADMIN_IDS: "Comma-separated list of admin user IDs"

  # Database Configuration
  DATABASE_URL: "PostgreSQL connection string for production"
  REDIS_URL: "Redis connection string (optional)"

  # Server Configuration
  SSH_PRIVATE_KEY: "Private SSH key for server access"
  SERVER_USER: "Username for server access"
  SERVER_HOST: "Server hostname or IP address"

  # Notification Configuration
  SLACK_WEBHOOK: "Slack webhook URL for notifications"

  # Package Publishing
  PYPI_API_TOKEN: "PyPI API token for package publishing"

  # Code Quality
  SONAR_TOKEN: "SonarCloud token for code analysis"

  # Monitoring
  HEALTH_CHECK_URL: "URL for health check endpoint"

# Environment Variables (can be set in workflow files)
env:
  # Python Configuration
  PYTHON_VERSION: "3.11"
  PIP_CACHE_DIR: "~/.cache/pip"

  # Docker Configuration
  DOCKER_REGISTRY: "ghcr.io"
  DOCKER_IMAGE: "antispam-bot"

  # Database Configuration
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_NAME: "antispam_bot"
  DB_USER: "antispam_bot"

  # Redis Configuration
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  # Logging Configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"

  # Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "3600"

# Usage Examples:
# 1. Set secrets in GitHub repository settings:
#    Settings > Secrets and variables > Actions > Repository secrets
#
# 2. Use in workflow files:
#    env:
#      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
#      ADMIN_IDS: ${{ secrets.ADMIN_IDS }}
#
# 3. Use in scripts:
#    export BOT_TOKEN="${{ secrets.BOT_TOKEN }}"
#    export ADMIN_IDS="${{ secrets.ADMIN_IDS }}"
