global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@antispam-bot.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/'

  - name: 'email'
    email_configs:
      - to: 'admin@antispam-bot.com'
        subject: '[AntiSpam Bot] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'telegram'
    webhook_configs:
      - url: 'https://api.telegram.org/bot{{ .BOT_TOKEN }}/sendMessage'
        send_resolved: true
        http_config:
          method: POST
        title: 'AntiSpam Bot Alert'
        text: |
          {{ range .Alerts }}
          🚨 *{{ .Annotations.summary }}*
          
          {{ .Annotations.description }}
          
          Severity: {{ .Labels.severity }}
          {{ end }}
