name: Backup

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    if: github.repository == 'your-username/antispam-bot'  # Change to your repo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Create backup archive
      run: |
        tar -czf antispam-bot-backup-$(date +%Y%m%d).tar.gz \
          --exclude='.git' \
          --exclude='__pycache__' \
          --exclude='*.pyc' \
          --exclude='.env' \
          --exclude='data/' \
          --exclude='logs/' \
          .

    - name: Upload backup to GitHub Releases
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.upload_url }}
        asset_path: ./antispam-bot-backup-$(date +%Y%m%d).tar.gz
        asset_name: antispam-bot-backup-$(date +%Y%m%d).tar.gz
        asset_content_type: application/gzip
