name: Basic Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  basic-test:
    name: Basic Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports
      env:
        BOT_TOKEN: "123456789:test_token_123456789"
        ADMIN_IDS: "123456789"
        DB_PATH: "test.db"
        REDIS_ENABLED: "false"
        REDIS_URL: "redis://localhost:6379/0"
      run: |
        python -c "
        print('Testing imports...')
        from app.config import load_config
        print('Config imported')
        config = load_config()
        print(f'Config loaded: Redis enabled = {config.redis_enabled}')
        print('SUCCESS: Basic test passed!')
        "
    
    - name: Test Redis service (without connection)
      env:
        BOT_TOKEN: "123456789:test_token_123456789"
        ADMIN_IDS: "123456789"
        DB_PATH: "test.db"
        REDIS_ENABLED: "false"
        REDIS_URL: "redis://localhost:6379/0"
      run: |
        python -c "
        print('Testing Redis service...')
        from app.services.redis import RedisService
        print('RedisService imported')
        service = RedisService('redis://localhost:6379/0')
        print('RedisService created')
        print('SUCCESS: Redis service test passed!')
        "
