name: Minimal Check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  minimal:
    name: Minimal Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test basic import
      env:
        BOT_TOKEN: "123456789:test_token_123456789"
        ADMIN_IDS: "123456789"
        DB_PATH: "test.db"
        REDIS_ENABLED: "false"
        REDIS_URL: "redis://localhost:6379/0"
      run: |
        python -c "
        print('Testing basic imports...')
        try:
            from app.config import load_config
            print('OK Config imported successfully')
        except Exception as e:
            print(f'ERROR Config import failed: {e}')
            exit(1)
        
        try:
            config = load_config()
            print(f'OK Config loaded: Redis enabled = {config.redis_enabled}')
        except Exception as e:
            print(f'ERROR Config load failed: {e}')
            exit(1)
        
        print('SUCCESS All basic tests passed!')
        "
