name: Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Health check
      run: |
        python - <<EOF
        import requests
        try:
            url = "https://example.com/health"  # TODO: заменить на рабочий домен
            r = requests.get(url, timeout=10)
            if r.status_code == 200:
                print("✅ Bot is healthy")
            else:
                print(f"⚠️ Bot returned status {r.status_code}")
        except Exception as e:
            print(f"⚠️ Health check failed: {e}")
        EOF
