name: Notify

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened]
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Placeholder step
      run: echo "Notifications disabled for now"
