name: Simple Check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  check:
    name: Basic Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports
      run: |
        python -c "
        print('Testing imports...')
        from app.config import load_config
        print('✅ Config imported')
        from app.services.redis import RedisService
        print('✅ Redis imported')
        from app.handlers.admin import admin_router
        print('✅ Handlers imported')
        print('✅ All imports successful!')
        "
    
    - name: Test basic functionality
      run: |
        python -c "
        from app.config import load_config
        config = load_config()
        print(f'✅ Config loaded: Redis enabled = {config.redis_enabled}')
        print(f'✅ Admin IDs: {len(config.admin_ids_list)}')
        print('✅ Basic functionality works!')
        "
