name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          This issue has been automatically marked as stale because it has not had recent activity.
          It will be closed if no further activity occurs. Thank you for your contributions.
        stale-pr-message: |
          This pull request has been automatically marked as stale because it has not had recent activity.
          It will be closed if no further activity occurs. Thank you for your contributions.
        close-issue-message: |
          This issue has been closed because it has been automatically marked as stale.
          If you believe this is an error, please reopen the issue.
        close-pr-message: |
          This pull request has been closed because it has been automatically marked as stale.
          If you believe this is an error, please reopen the pull request.
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-stale: 30
        days-before-close: 7
        exempt-issue-labels: 'bug,security,priority:high,priority:critical'
        exempt-pr-labels: 'bug,security,priority:high,priority:critical'
        only-issue-labels: ''
        only-pr-labels: ''
        operations-per-run: 100
        remove-stale-when-updated: true
        debug-only: false
